version: '3.8'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: foodpanda-playlist

  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080