// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

// Stores playlist
type Playlist struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsPublic    sql.NullBool   `json:"is_public"`
	DeliveryDay sql.NullString `json:"delivery_day"`
	Category    sql.NullString `json:"category"`
}

// Stores playlist restaurant items
type PlaylistRestaurantItem struct {
	ID                     int64         `json:"id"`
	PlaylistID             sql.NullInt32 `json:"playlist_id"`
	RestaurantItemID       sql.NullInt32 `json:"restaurant_item_id"`
	RestaurantItemQuantity sql.NullInt32 `json:"restaurant_item_quantity"`
	AddedAt                sql.NullTime  `json:"added_at"`
}

// Stores restaurants
type Restaurant struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Location    sql.NullString `json:"location"`
	Cuisine     sql.NullString `json:"cuisine"`
	ImageUrl    sql.NullString `json:"image_url"`
}

// Stores restaurant items
type RestaurantItem struct {
	ID           int64          `json:"id"`
	RestaurantID sql.NullInt32  `json:"restaurant_id"`
	IsAvailable  sql.NullBool   `json:"is_available"`
	Name         sql.NullString `json:"name"`
	Description  sql.NullString `json:"description"`
	Price        sql.NullString `json:"price"`
	Cuisine      sql.NullString `json:"cuisine"`
	ImageUrl     sql.NullString `json:"image_url"`
}

// Stores user data
type User struct {
	ID           int64          `json:"id"`
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Address      sql.NullString `json:"address"`
}

// Stores user playlist
type UserPlaylist struct {
	ID           int64          `json:"id"`
	UserID       sql.NullInt32  `json:"user_id"`
	PlaylistID   sql.NullInt32  `json:"playlist_id"`
	DeliveryDay  sql.NullString `json:"delivery_day"`
	DeliveryTime sql.NullString `json:"delivery_time"`
	Status       sql.NullString `json:"status"`
}
