// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: restaurant.sql

package db

import (
	"context"
	"database/sql"
)

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (
  name,
  description,
  location,
  cuisine,
  image_url
) 
VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, description, location, cuisine, image_url
`

type CreateRestaurantParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Location    sql.NullString `json:"location"`
	Cuisine     sql.NullString `json:"cuisine"`
	ImageUrl    sql.NullString `json:"image_url"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, createRestaurant,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.Cuisine,
		arg.ImageUrl,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Cuisine,
		&i.ImageUrl,
	)
	return i, err
}

const deleteRestaurant = `-- name: DeleteRestaurant :exec
DELETE FROM restaurants
WHERE id = $1
`

func (q *Queries) DeleteRestaurant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRestaurant, id)
	return err
}

const getRestaurant = `-- name: GetRestaurant :one
SELECT id, name, description, location, cuisine, image_url FROM restaurants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRestaurant(ctx context.Context, id int64) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, getRestaurant, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Cuisine,
		&i.ImageUrl,
	)
	return i, err
}

const listRestaurants = `-- name: ListRestaurants :many
SELECT id, name, description, location, cuisine, image_url FROM restaurants
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListRestaurantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRestaurants(ctx context.Context, arg ListRestaurantsParams) ([]Restaurant, error) {
	rows, err := q.db.QueryContext(ctx, listRestaurants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Restaurant
	for rows.Next() {
		var i Restaurant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Cuisine,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRestaurant = `-- name: UpdateRestaurant :one
UPDATE restaurants
SET 
  name = $2,
  description = $3,
  location = $4,
  cuisine = $5,
  image_url = $6
WHERE 
  id = $1
RETURNING id, name, description, location, cuisine, image_url
`

type UpdateRestaurantParams struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Location    sql.NullString `json:"location"`
	Cuisine     sql.NullString `json:"cuisine"`
	ImageUrl    sql.NullString `json:"image_url"`
}

func (q *Queries) UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, updateRestaurant,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.Cuisine,
		arg.ImageUrl,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Cuisine,
		&i.ImageUrl,
	)
	return i, err
}
